[package]
name = "porsmo"
version = "0.1.0"
edition = "2021"
readme = "README.org"
description = "A pomodoro and time and countdown, all in one app"
keywords = ["cli", "pomodoro", "timer", "countdown"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
anyhow = "1.0"
termion = "*"
notify-rust = "4"
rodio = "0.12.0"
